#端口号
server:
    port:8080

# 数据源配置
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yd_cloud?serverTimezone=GMT%2B8
        username: root
        password: root

# 二级缓存默认配置
doublecache:
    allowNull: true
    init: 128
    max: 1024
    caffeineExpire: 5 # Caffeine缓存过期时间
    redisExpire: 10 # redis缓存过期时间